version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./Back
    container_name: Back
    env_file: ./Back/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./Front
    container_name: Front
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
